services:
  attester:
    git: "https://github.com/cloudflare/pp-attester"
    port: "8788"
  issuer:
    url: "https://pp-issuer-public.research.cloudflare.com"
  origin:
    file: "./pp-origin"
    port: "8789"

config:
  directory: ".dist"
