services:
  attester:
    git: "git@github.com:cloudflare/pp-attester.git"
    port: "8788"
  issuer:
    url: "https://pp-issuer-public.research.cloudflare.com"
  origin:
    file: "../pat-origin"
    port: "8789"

config:
  directory: "dist"
